name: causal_rl_bench
channels:
- conda-forge
dependencies:
- python=3.7.4
- numpy==1.18.1
- pinocchio==2.2.2
- tensorflow==1.14.0
- sphinx
- jupyter
- pip:
  - pybullet
  - gym
  - namegenerator
  - pandas
  - mpi4py
  - joblib
  - catkin_pkg
  - sphinx_rtd_theme
  - stable-baselines==2.10.0