name: causal_rl_bench
channels:
- conda-forge
dependencies:
- python=3.7.4
- sphinx
- pytorch-cpu=1.2
- jupyter
- pip:
  - pybullet==2.8.2
  - gym
  - pandas
  - catkin_pkg
  - sphinx_rtd_theme
  - tensorflow==1.14.0
  - stable-baselines==2.10.0
  - pytest
  - mpi4py
  - psutil
  - pyprind
  - torch==1.2.0