name: causal_rl_bench
channels:
- conda-forge
dependencies:
- python=3.7.4
- sphinx
- jupyter
- pip:
  - pybullet==2.8.2
  - gym
  - pandas
  - catkin_pkg
  - sphinx_rtd_theme
  - pytest
  - mpi4py
  - psutil