name: causal_world
channels:
- conda-forge
dependencies:
- python=3.7.4
- sphinx
- jupyter
- scipy
- pip:
  - pybullet==3.2.5
  - gym==0.17.2
  - catkin_pkg
  - sphinx_rtd_theme
  - pytest
  - psutil
  - sphinxcontrib-bibtex