name: causal_rl_bench
channels:
- conda-forge
dependencies:
- python=3.7.4
- pinocchio==2.2.2
- sphinx
- jupyter
- pip:
  - pybullet
  - gym
  - pandas
  - catkin_pkg
  - sphinx_rtd_theme
  - tensorflow==1.14.0
  - stable-baselines==2.10.0
