name: causal_rl_bench
channels:
- pytorch
- anaconda
- conda-forge
dependencies:
- python=3.7.4
- cython
- ipython
- numpy==1.18.1
- pinocchio==2.2.2
- pip:
  - pybullet
  - gym
  - tensorflow==1.14.0
  - namegenerator
  - pandas
  - mpi4py
  - joblib
  - opencv-python
  - catkin_pkg
