version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run: conda env create -f environment.yml
      - run: conda activate causal_world
      - run: pip install -e .
      - run: python -m unittest discover tests/causal_world/
      
workflows:
  main:
    jobs:
      - build-and-test
